

- name: Add Grafana GPG key
  ansible.builtin.apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present

- name: Add Grafana APT repository
  ansible.builtin.apt_repository:
    repo: "deb https://packages.grafana.com/oss/deb stable main"
    state: present

- name: Install Grafana
  ansible.builtin.apt:
    name: grafana
    state: present

- name: Template datasources
  ansible.builtin.copy:
    src: templates/datasources.yaml
    dest: /etc/grafana/provisioning/datasources/default.yaml
  notify: Restart grafana

- name: Move template dashboards
  ansible.builtin.copy:
    src: templates/dashboards.yaml
    dest: /etc/grafana/provisioning/dashboards/dashboard.yaml
  notify: Restart grafana
  
- name: Copy main json
  ansible.builtin.copy:
    src: files/main.json
    dest: /etc/grafana/provisioning/dashboards/main.json
  notify: Restart grafana

- name: Copy syslog json
  ansible.builtin.copy:
    src: files/syslog.json
    dest: /etc/grafana/provisioning/dashboards/syslog.json
  notify: Restart grafana

- name: Copy backups json
  ansible.builtin.copy:
    src: files/backups.json
    dest: /etc/grafana/provisioning/dashboards/backups.json
  notify: Restart grafana

- name: Copy mysql json
  ansible.builtin.copy:
    src: files/mysql.json
    dest: /etc/grafana/provisioning/dashboards/mysql.json
  notify: Restart grafana

- name: Grafana config
  template:
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini
    mode: '0644'
  no_log: true
  notify: Restart grafana

- name: Ensure grafana is running
  ansible.builtin.service:
    name: grafana-server
    state: started
    enabled: true