{
 "title": "Backups",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Time from last MySQL backup",
   "type": "stat",
   "gridPos": { "h": 5, "w": 13, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - backup_last_success_time{user=\"olegas2006\", service=\"mysql\"}+5",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time from last InfluxDB backup",
   "type": "stat",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - backup_last_success_time{user=\"olegas2006\", service=\"influxdb\"}+5",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MySQL incremental backups",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 13, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "backups_total{user=\"olegas2006\", service=\"mysql\", type=\"incremental\"}\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "InfluxDB incremental backups",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "backups_total{user=\"olegas2006\", service=\"influxdb\", type=\"incremental\"}\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MySQL full backups",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 13, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "backups_total{user=\"olegas2006\", service=\"mysql\", type=\"full\"}\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "InfluxDB full backups",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 11, "x": 13, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "backups_total{user=\"olegas2006\", service=\"influxdb\", type=\"full\"}\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}