{
 "title": "Main",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Haproxy status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "haproxy_up", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Container status (haproxy 1)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "haproxy_server_up{instance = \"lb-1:9101\"}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Container status (haproxy 2)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "haproxy_server_up{instance = \"lb-2:9101\"}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "BIND status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bind_up", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Keepalived status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "keepalived_up{instance= \"lb-1:9165\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "VRRP 1",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "keepalived_vrrp_state{instance =\"lb-1:9165\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "NGINX status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nginx_up", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "MYSQL status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_up{instance =~\"db-1:9104|db-2:9104\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Keepalived status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "keepalived_up{instance= \"lb-2:9165\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "VPPR 2",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "keepalived_vrrp_state{instance =\"lb-2:9165\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1-rate(node_cpu_seconds_total{mode=\"idle\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{instance!=\"localhost:9100\"} - node_memory_MemFree_bytes{instance!=\"localhost:9100\"} - node_memory_Cached_bytes{instance!=\"localhost:9100\"} - node_memory_Buffers_bytes{instance!=\"localhost:9100\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Other AGAMAs item count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "query": "SELECT cumulative_sum(SUM(\"items\")) FROM \"agama-stats\" \nWHERE $timeFilter \nGROUP BY time(20s) fill(null);\n"
    }
   ]
  },
  {
   "title": "MYSQL SELECTs per minute",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "rate(mysql_global_status_commands_total{command=\"select\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "NGINX requests per minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "My AGAMA items count(main)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT \"items\" FROM \"agama-stats\" WHERE \"name\" = 'olegas2006-1.infroha.ro.';\n"
    }
   ]
  },
  {
   "title": "My AGAMA items count(replica)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT \"items\" FROM \"agama-stats\" WHERE \"name\" = 'olegas2006-2.infroha.ro.';\n"
    }
   ]
  },
  {
   "title": "DNS queries per minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "rate(bind_resolver_queries_total{type=~\"NS|A\"}[1m])",
     "legendFormat": "{{instance}}, {{type}}"
    }
   ]
  }
 ]
}