
- name: Restart bind9
  service:
    name: bind9
    state: restarted

- name: rndc reload bind9
  ansible.builtin.command: rndc reload
  changed_when: true

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true