#- name: Ansible ping module
#  ansible.builtin.ping:

#- name: Create user juri
#  ansible.builtin.user:
#    name: juri

#- name: Create key for juri
#  ansible.posix.authorized_key:
#    user: juri
#    state: present
#    key: https://github.com/hudolejev.keys
  
#- name: Create user roman
#  ansible.builtin.user:
#    name: roman

#- name: Create key for roman
#  ansible.posix.authorized_key:
#    user: roman
#    state: present
#    key: https://github.com/romankuchin.keys

- name: Update APT cache
  ansible.builtin.apt:
    cache_valid_time: 86400

- name: Install Prometheus node exporter
  ansible.builtin.apt:
    name: prometheus-node-exporter
    state: present

- name: Start prometheus-node-exporter service
  systemd:
    name: prometheus-node-exporter
    state: started
    enabled: yes

- name: Copy rsyslog configurarion file
  template:
    src: 50-telegraf.conf.j2
    dest: /etc/rsyslog.d/50-telegraf.conf
  notify: Restart rsyslog

- name: Start rsyslog service
  systemd:
    name: rsyslog
    state: started
    enabled: yes

- name: Create user 'backup'
  user:
    name: backup
    home: /home/backup
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: /home/backup/.ssh/id_rsa
    shell: /bin/bash
  become: yes

- name: Template backup
  ansible.builtin.template:
    src: backup_known_host.j2
    dest: /home/backup/.ssh/known_hosts
    owner: backup
    group: backup
    mode: '0644'

- name: Ensure /home/backup/restore directory is created
  file:
    path: /home/backup/restore
    state: directory
    owner: backup
    group: backup
    mode: '0755'
  no_log: true

- name: Ensure Duplicity is installed
  apt:
    name: duplicity
    state: present

